# 서버 포트
server:
  port: 8081

# 마이크로서비스 명칭, DB 설정  
spring:  application:    name: member
    
  datasource:    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
     
  h2:    console:      enabled: true

  cloud:
    loadbalancer:      retry:        enabled: true

# hystrix timeout 기본 1초 -> 3초
hystrix:
  command:
    getWorkInfo:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      metrics: #circuit breaker가 10초내
        rollingStats:
          timeInMilliseconds: 10000
      circuitBreaker: #circuitBreaker 설정 (5초내 요청수 : 기본 20 -> 5개, 실패확률 : 기본 50%)
        requestVolumeThreshold: 5
        errorThresholdPercentage: 50

    getMemberAndWorkInfo:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      metrics: #circuit breaker가 10초내
        rollingStats:
          timeInMilliseconds: 10000
      circuitBreaker: #circuitBreaker 설정 (5초내 요청수 : 기본 20 -> 5개, 실패확률 : 기본 50%)
        requestVolumeThreshold: 5
        errorThresholdPercentage: 50
        
# hystrix dashborad 가시화를 위한 설정
management:  endpoints:    web:      exposure:        include:        - "*"
        
# ribbon loadbalance
work:
  ribbon:
    #listOfServers: localhost:8082, localhost:7777
    MaxAutoRetries: 0 # 동일한 서버로 재시도 횟수
    MaxAutoRetriesNextServer: 1 # 실패시 다른 서버로 재시도 횟수
    OkToRetryOnAllOperations: true # 무엇이든 모든 동작들은 재시도 가능
    
# eureka client 관련 설정
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
